### ISSUE TITLE
Homepage - all section: bullet navigation for slider is not implemented in mobile view

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Ansell-Strategic#57]
Why Choose, Case Studies and Latest News and Publications

![image](https://cloud.githubusercontent.com/assets/17717843/15003531/5c7ac5ee-11df-11e6-9f9b-f52de45ad178.png)

**Comment by algericotitandigital** [comment]
There is a plugin issue if we will display 2 items in why choose us section. This will be the same for testimonials sections as it display 1 item.
